# Write a function so that columns of output matrix are powers of the input vector.
the orders of the powers is determined by the increasing boolean argument. Specifically when increasing is False, the i-th output column is the input vector raised element-wise to the power of N-i-1.


In [24]:
import numpy as np
##default value of N as None and increasing to False
def vandermode(inlist, N = None, increasing = False):
    if N==None:
       N = len(inlist)
    if increasing==False:
        print("decreasing powers from", N)
        result=[[pow(num, N-i-1) for i in range(N)] for num in inlist ]
        print(np.asanyarray(result))
    else:
        print("increasing powers till", N)
        result=[[pow(num, i) for i in range(N)] for num in inlist ]
        print(np.asanyarray(result))

vandermode([1,2,4], N = 10, increasing = False)

decreasing powers from 10
[[     1      1      1      1      1      1      1      1      1      1]
 [   512    256    128     64     32     16      8      4      2      1]
 [262144  65536  16384   4096   1024    256     64     16      4      1]]


## Problem Statement
Given a sequence of n values x1,x2...xn and a window size k>0, the kth moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving average with k=4 of a ten value sequence is shown below.
i     1 2 3 4 5 6 7 8 9 10
--    ---------------------
input 10 20 30 40 50 60 70 80 90 100
y1    25=(10+20+30+40)/4
y2    35=(20+30+40+50)/4
y3    45=(30+40+50+60)/4
y4    55=(40+50+60+70)/4
y5    65=(50+60+70+80)/4
y6    75=(60+70+80+90)/4
y7    85=(70+80+90+100)/4
Thus, the moving average sequence has n-k+1 = 10-4+1=7 values

In [74]:
import numpy as np
def movingAvg(ilist,k=1):
    Ylen=len(ilist)-k+1
    Fullarray=[[ilist[i] for i in range(j,j+k)] for j in range(Ylen) ]
    Y=[np.average(x) for x in Fullarray]
    print("The moving average of sequence %s and window size value %d is:\n %s\n" % (ilist, k,  Y))
    
##moving average of 6 values of value k=3
movingAvg([10,20,30,40,50,60,70,80,90,100],4)

##moving average of 6 values of value k=3    
movingAvg([20,30,40,50,60,70],3)

The moving average of sequence [10, 20, 30, 40, 50, 60, 70, 80, 90, 100] and window size value 4 is:
 [25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]

The moving average of sequence [20, 30, 40, 50, 60, 70] and window size value 3 is:
 [30.0, 40.0, 50.0, 60.0]

